### ISSUE TITLE
[QUESTION] How to retrieve total number of messages without iterating through the entire chat?

### ISSUE THREAD

**Issue by Alyetama** [xenova/chat-downloader#113]
## What is your question?
How can I find the total number of messages in a past twitch stream given id or url without having to iterate over all the messages from the generator? In other words, is there a way to just return the total number of messages that were sent in a twitch stream?

**Comment by xenova** [comment]
Unfortunately, I don't think so. If there isn't a way to do this from Twitch itself (i.e., on the website) and there isn't a way to do it with their API, then I think the only way to count the number of messages would be to iterate over all messages.

There might be an undocumented endpoint, but I am not aware of it.

The way Twitch gets chat messages us with the https://api.twitch.tv/v5/videos/<video_id>/comments endpoint.

For example, https://api.twitch.tv/v5/videos/1098742950/comments?client_id=kimne78kx3ncx6brgo4mv6wki5h1ko&cursor=eyJpZCI6ImI5ZmNkNThjLTU4OTctNDU3Mi05NTNkLTQ0ZDFjNzhjZDMxMSIsImhrIjoiYnJvYWRjYXN0OjQyNzU3NDE0NDYwIiwic2siOiJBQUFBSC1VZV93QVdsV1l6dUdfRUFBIn0f&content_offset_seconds=0

where:
- client_id=kimne78kx3ncx6brgo4mv6wki5h1ko is the public client id for all unauthenticated requests
- cursor=<something> is a base64 representation of what you are requesting (e.g., the above decodes to `{"id":"b9fcd58c-5897-4572-953d-44d1c78cd311","hk":"broadcast:42757414460","sk":"AAAAH-Ue_wAWlWYzuG_EAA"}`), where 'id' is the first message id to get and 'hk' encodes the video id. To be honest, I'm not sure what 'sk' is, but it probably represents how many messages to get? (This might be able to help you, though, I'm not too sure)
- content_offset_seconds=<something> is just the number of seconds to offset the result by (useful when seeking)

---

So, there might be a clever way to do it, but the simplest would be to iterate over.

If your problem is that it is taking too long to count the number of messages, you could perhaps try split the stream into different parts (e.g., if the video is 1000 seconds long, you could run 4 instances simultaneously, each doing 250 seconds each). I can give some example code if this would help.

Alternatively, if you just need a rough estimate, you could maybe calculate the number "messages per second" for each iteration, and multiply that by the total duration and then stop after a few iterations. Unfortunately, chat speeds vary, so this probably won't be the best solution.
