### ISSUE TITLE
[QUESTION] Improvements recommendations 

### ISSUE THREAD

**Issue by vanyamlb** [xenova/chat-downloader#119]
So... I'll tell you the story. Me and my friend decided to improve the tool and integrate 2 tools in one. How it worked before the trouble:

there is a tool that used your code to download the chat, BUT with the following features:

1. scanning channels automatically
2. scanning playlists automatically
3. skipping already existing downloaded chats

It works through YouTube API. You enter the channel/playlist id and the number of vods you need to download and it downloads all of them that contains the chat and skips the rest of them, as the tool does video listing on the channel through the API requests.

The tool stopped working with that emoji error and sadly it's much harder to integrate the newest version of your chat downloader with that tool because you completely changed it :(

**Comment by vanyamlb** [comment]
heeyyy, any updates on this? @xenova

**Comment by xenova** [comment]
Well, I'm not too sure what you want me to do?

If you need help reintegrating, you can ask a question and I'll try answer. Or, if you would like me to add some features, you can ask and I might be able to add it.

Otherwise, I do believe you should be able to convert your old code to use the new library. Although the implementation has changed, the interface should be similar to use. For an example, check out the code snippet in the README.
