### ISSUE TITLE
[QUESTION] Iterating over the chat messages is too slow

### ISSUE THREAD

**Issue by NikolasPpd** [xenova/chat-downloader#148]
## What is your question?
Using a simple for loop
```
for message in chat:
  pass
```
I'm iterating over approximately 14,000 chat messages and using the for loop above takes around 35 seconds. It seems to me that it's very slow. Is there anything I can do to speed this up?

**Comment by xenova** [comment]
Unfortunately not. YouTube provides the data in a sequential manner, so you have to get the first batch to get the next (this is done using a "continuation" parameter)

**Comment by NikolasPpd** [comment]
It's okay. It's not really a problem at this scale. I was just curious if it could be optimized for a much larger scale. Thanks for the answer though!

**Comment by xenova** [comment]
I should mention one possible solution though, and that is to use start and end times to get different sections of the chat, and then combining them at the end.
You can do this with the `--start` and `--end` arguments.

However, this still has the problem of getting data sequentially in between these times (discussed above).

So, depending on your use-case, I suppose you could parallelise extraction in this way, but just remember to not go "overboard" since YouTube might throttle requests made from your IP.
