### ISSUE TITLE
[QUESTION] Videos for testing

### ISSUE THREAD

**Issue by BleachedGorilla** [xenova/chat-downloader#154]
## What is your question?
Was watching a recent livestream that had over 3.5M live viewers. It is a great video to use to test the performance of the script.

Link to video: https://www.youtube.com/watch?v=sThZ4TZ_Py4

Do you have any other examples like that video to test upon?

**Comment by mikelei8291** [comment]
https://github.com/xenova/chat-downloader/blob/2a5b3f50d57beb36595ae838d989df4235b80124/chat_downloader/sites/youtube.py#L70

The code is [always tested](https://github.com/xenova/chat-downloader/blob/master/.github/workflows/python-package.yml) on each commit so I'm not sure what else would you like to be tested?

**Comment by xenova** [comment]
@BleachedGorilla Thanks for the info 👍  As @mikelei8291 mentioned, I try to keep an up-to-date list of URLs for testing in the `_TESTS` list (same way yt-dlp does it).

Since the video is ~9h long, we can't run it everytime for testing. That being said, I ran it once on my computer and everything seems to work fine. If you would like to do the same in future, you can run it with the `--testing` flag (which will pause if it encounters anything *strange*).

I'll close the issue for now, but feel free to ask any other questions.
