### ISSUE TITLE
python flag for `--output` to export chats to json?

### ISSUE THREAD

**Issue by atnjqt** [xenova/chat-downloader#66]
is there a python flag for `--output` so I can export chats to json?

I see this in the CLI documentation (you included `-o` flag in your cmd) but not for the `ChatDownloader().get_chat()` ... I need this json so I can pd.read_json for ETL of chat data

``` 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-106-472d1877d159> in <module>
----> 1 chat = ChatDownloader().get_chat(url=url,message_types=["text_message", "paid_message", "membership_item"],output=outfile)

TypeError: get_chat() got an unexpected keyword argument 'output'
```

__Originally posted by @atnjqt in https://github.com/xenova/chat-downloader/issues/61#issuecomment-778847756__

**Comment by xenova** [comment]
Hi there!

This functionality has been included in the code, but not in the `get_chat` method. The `get_chat` method was only responsible for returning a an iterable `Chat` object (hence the `get` in the name). This `Chat` object has the ability to generate more messages (using http requests) when needed.

File output and other more advanced processing should be the responsibility of the user implementing the code. That being said, there are ways to use the module's outputting functionality as I will describe later.

Early into development, users wanted a way to continuously write to file. Since this is not standard functionality for file IO in python, the [continuous_write.py](https://github.com/xenova/chat-downloader/blob/master/chat_downloader/output/continuous_write.py) module was created.

Now, there are many ways to use this, but I will describe 2:

1. Using `ContinuousWriter`
```python
from chat_downloader import ChatDownloader
from chat_downloader.output.continuous_write import ContinuousWriter

# We now create a ContinuousWriter object and set options. Different
# options are allowed for different output formats:
#
# - JSON: file_name, overwrite=False, indent=None, separator=', ', indent_character=' ', sort_keys=True
# - CSV: file_name, overwrite=False, sort_keys=True
# - TXT: file_name, overwrite=False
#
# All values except file_name are optional, and assume the default values listed above


file_name = 'output.json' # or 'output.csv' or 'output.txt'

writer = ContinuousWriter(file_name, overwrite=True)

url = 'https://www.youtube.com/watch?v=5qap5aO4i9A'
chat = ChatDownloader().get_chat(url)   # create a generator

try:
    for message in chat:                    # iterate over messages
        writer.write(message)
        print(chat.format(message))         # print the formatted message
finally:
    writer.close()

```

2. Using `run`.
Alternatively, if your program's functionality matches that of the command line interface, you can "simulate" running it from the command line using the `run(**kwargs)` method:
```python
from chat_downloader import run

url = 'https://www.youtube.com/watch?v=5qap5aO4i9A'
file_name = 'output.json'  # or 'output.csv' or 'output.txt'
run(
    url=url,
    output=file_name,
    overwrite=True
)
```
This option is less suitable if you need more control.

**Comment by atnjqt** [comment]
Thanks for the reply, @xenova -- The `run` command works really nicely for my use case:

``` python
def chat_downloader_run_all(youtube_url):
    
    # pass url as arg
    url = youtube_url
    
    # set your message types of interest
    msg_types = ["text_message", "paid_message", "membership_item"]
    
    # set your outfile based on youtube videoID
    outfile = './data/raw/{}.json'.format(url.split("watch?v=")[-1])  # or 'output.csv' or 'output.txt'
    
    # run the chat_downloader
    run(
        url=url,
        message_types=msg_types,
        output=outfile,
        overwrite=True
    )
    
    return
```

Specifically, I am looping through a YouTube video playlist with 290+ URLs (turns out only 180 of which had live chat enabled)... It would be convenient to include a kwarg to suppress std output if writing to output, the print crashed my notebook...

After exporting each URL to respective json, I can proceed with reading into a pd.dataframe() and do some string operations to try and extract **USD totals** (I exclude foreign currency here, though I am certain someone who is better with regexp can get currency & val from the `amount.values` column)

``` python
json_files = []

for json_file in [item for item in os.listdir('./data/raw/') if item.endswith('.json')]:
    df = pd.read_json('./data/raw/{}'.format(json_file))
    json_files.append(df)
    
# concat all json files into combined df
chat_df = pd.concat(json_files)

# find all rows where the first letter is $ , 
# then replace that with empty string and set as new col named USD with floats
chat_df['USD'] = chat_df[chat_df.amount.str[0] == '$'].amount.str.replace('$','').astype(float)

# you can then get superchat donation totals for paid_messages
yt_chatetl_df['USD'].sum()
```

Not that you needed to know my usecase but though it is worth sharing as a python example... Thanks again 👍

**Comment by xenova** [comment]
You can suppress output using the "quiet" argument.

```python

run(
        url=url,
        message_types=msg_types,
        output=outfile,
        overwrite=True,
        quiet=True
    )

```

This will make it so that no messages are printed.

For more info on what parameters are available, run:
```
chat_downloader -h
```

---

It's cool to hear about your use case 👍 Always nice to hear how people are using the tool! 🔥💪

Let me know if you have any other questions.

**Comment by atnjqt** [comment]
of course a `quiet` arg makes sense, thanks for this! I missed that when skimming through the documentation ...

**Comment by xenova** [comment]
> of course a `quiet` arg makes sense, thanks for this! I missed that when skimming through the documentation ... 

No worries! Yeah, the documentation still needs a lot of work... 😅
