### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by teisseire117** [xenova/chat-downloader#69]
Hi,

I'm a newbie at programmation/python, so my apologize if the answer may seem obvious to you. Although, I want to note that I spent about an hour searching before making this post.

I'm trying to access to messages, and the user_name user_id that wrote them, as well as the timestamp. For example :` chat[0]['message']` would be the message`, chat[0]['author_id']` would be the author id of message 0 etc.

I've been trying so many things but I don't seem to find out where to access these informations. The only thing I managed to find is through `print(chat.__dict__)` which returns

`{'chat': <generator object YouTubeChatDownloader._get_chat_messages at 0x00000212F4299200>, 'title': 'lofi hip hop radio - beats to relax/study to', 'duration': 0, 'is_live': True, 'start_time': 1613511041254733.0, 'site': <chat_downloader.sites.youtube.YouTubeChatDownloader object at 0x00000212F48755E0>, 'format': <function ChatDownloader.get_chat.<locals>.<lambda> at 0x00000212F487E160>}`

But I'm not sure to understand, and on first look it doesn't seem to list the informations I can retrieve about messages

I also would like to know if there's a list of every information we're able to access(message, author_id, message_type, author_name, timestamp etc..)

Thank you !
PS:It's for Youtube chat replay
PS2: I was asked to label it as 'Bug' or 'Feature' and I didn't really know what to pick.

**Comment by taizan-hokuto** [comment]
You can retrieve author id by this:
```
from chat_downloader import ChatDownloader

url = 'https://www.youtube.com/watch?v=5qap5aO4i9A'
chat = ChatDownloader().get_chat(url) 
for message in chat:
    print(message["author"]["id"])
```

the `message` (in the original script described as `data`, yielded from `chat_downloader.sites.youtube.py#_get_chat_messages()`) is `dict`, and it has below keys:
```
{
 'action_type', 
 'message', 
 'message_id', 
 'timestamp', 
 'author': {'id', 'name', 'images':[{'url', 'width', 'height', 'id'},...}, 
 'message_type'
}
```

e.g. you can retrieve author's icon url by this:
```
from chat_replay_downloader import ChatDownloader
url = 'https://www.youtube.com/watch?v=5qap5aO4i9A'
chat = ChatDownloader().get_chat(url) 
for message in chat:
    print(message["author"]["images"][0]["url"])    
```

**Comment by xenova** [comment]
Hi @teisseire117 - yes, @taizan-hokuto is absolutely right! I'll explain what is returned by the `get_chat` method.


When running
```python
chat = ChatDownloader.get_chat('url')
```
you will notice that it returns very quickly (after initialisation). This is because it returns a **generator** object (I'd recommend googling what these are - they are super useful!). In fact, the object has a `chat` attribute which is the actual generator controlling it, which you saw after running `chat.__dict__`.

This ensures that `chat`  is now iterable. In other words, we can loop over it:
```python
for message in chat:
    print(message)                                  # This prints the actual json of the chat message
    author = message['author']                      # Returns a dictionary with more items
    author_id = author['id']
    author_name = author['name']

```

The reason generators are better to use in this case, is because we sometimes do not know when the chat will end, so we can continue generating the messages until there are no more. This also makes it much easier to deal with instead of waiting for 5 minutes and then getting all messages as a list.

---
```
{'chat': <generator object YouTubeChatDownloader._get_chat_messages at 0x00000212F4299200>, 'title': 'lofi hip hop radio - beats to relax/study to', 'duration': 0, 'is_live': True, 'start_time': 1613511041254733.0, 'site': <chat_downloader.sites.youtube.YouTubeChatDownloader object at 0x00000212F48755E0>, 'format': <function ChatDownloader.get_chat.<locals>.<lambda> at 0x00000212F487E160>}```

Moving on, we have `title`, 'duration`, `is_live` and `start_time`. These are self-explanatory.

The `site` attribute is the actual "ChatDownloader" that is created and controls the retrieval of messages. These are located in `chat_downloader.sites`.

Lastly, the `format` is a function which formats the messages based on the `format` and `format_file` passed to `get_chat`.

---


> I also would like to know if there's a list of every information we're able to access(message, author_id, message_type, author_name, timestamp etc..)

I have been working to include this in the documentation! For now, you can just print out the json of the message and see yourself.

Also, I understand that the tool is lacking documentation - and I am working hard to get it done!

**Comment by teisseire117** [comment]
@taizan-hokuto @xenova This is perfect, thank you both for your time !
