### ISSUE TITLE
[BUG] "currency":"¥"

### ISSUE THREAD

**Issue by teisseire117** [xenova/chat-downloader#71]
Hi,

I was wondering if it's possible that you change the '¥' to 'YEN' to make it consistent with how others currency are named.
```
{'text': '£4.99', 'amount': 4.99, 'currency': 'GBP', 'currency_symbol': '£'}
{'text': '$5.00', 'amount': 5.0, 'currency': 'USD', 'currency_symbol': '$'}
{'text': '¥1,000', 'amount': 1000.0, 'currency': '¥', 'currency_symbol': '¥'}
```

$ it's USD, £ GBP, but for ¥ it seems to remain ¥

Thank you

EDIT: 

Oh! I was looking into the files and I found this         '￥': 'JPY', it represents the same symbol but it's still a different character

**Comment by xenova** [comment]
Oh wow that's strange! Let me get that fixed. Can you provide me with the URL you tested with?

**Comment by teisseire117** [comment]
> Oh wow that's strange! Let me get that fixed. Can you provide me with the URL you tested with?

https://www.youtube.com/watch?v=75dUDnCujT4

**Comment by xenova** [comment]
```{'money': {'amount': 1000.0, 'currency': 'JPY', 'currency_symbol': '¥', 'text': '¥1,000'}}```

Okay: b639ba8 fixes it :)

**Comment by xenova** [comment]
Turns out there are two symbols for the yen:

According to https://en.wikipedia.org/wiki/Yen_and_yuan_sign:
The Unicode code point is U+00A5 ¥ YEN SIGN (HTML &#165; · &yen;). Additionally, there is a full width character, ￥, at code point U+FFE5 ￥ FULLWIDTH YEN SIGN (HTML &#65509;)[a] for use with wide fonts, especially East Asian fonts.

**Comment by xenova** [comment]
I also added support for the full-width variant of the South Korean won (￦).
